### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by trebmuh** [jpcima/HybridReverb2#1]
J'ai ouvert 2 ou 3 fichiers source et il semble bien que la licence soit GPL 2.
Ça serait utile d'avoir un fichier LICENCE à la racine.

**Comment by jpcima** [comment]
GPLv2 ou, au choix, toute version ultérieure.
Je vais mettre : le texte de la v2, le texte de la v3, et une mention de la double licence comme préconisé sur le mode d'emploi. https://www.gnu.org/licenses/gpl-2.0.html

**Comment by trebmuh** [comment]
nickel
