### ISSUE TITLE
Construction sans GUI ?

### ISSUE THREAD

**Issue by trebmuh** [jpcima/HybridReverb2#2]
Je viens de tenter une construction dont [voici le log](http://paste.debian.net/1030467/). Malheureusement, il semble que je n'ai pas de GUI si j'en crois jalv lorsque je le lance avec la commande : `jalv.gtk3 https://github.com/jpcima/HybridReverb2`.

J'ai ces paquets d'installés : `cmake libasound2-dev libfftw3-dev libfreetype6-dev libgtk-3-dev libjack-jackd2-dev libxext-dev libx11-dev pkg-config`

Tu vois quelque chose d'évident que je loupe ?

**Comment by jpcima** [comment]
> Tu vois quelque chose d'évident que je loupe ?

Hélas non. Je teste moi même dans Jalv en GTK2 et en GTK3, et dans les deux cas cela fonctionne.

D'une part, `CMAKE_BUILD_TYPE` est à définir à `Release`, sans quoi les performances seront atroces. Au démarrage, tu as une pré-initialisation qui précède la GUI et demande un certain temps d'exécution (rien d'extraordinaire non plus).

1. indique moi stp la sortie de Jalv
2. version de Jalv
2. si le problème se reproduit en version VST

Je m'installe une LibraZiK dans Virtualbox afin de bien tester.

**Comment by trebmuh** [comment]
Comment je fais pour définir le CMAKE_BUILD_TYPE à Release ? C'est une option en CLI du configure ou bien dois-je modifier un fichier ?

1. voilà:
```
$ jalv.gtk3 https://github.com/jpcima/HybridReverb2
Plugin:       https://github.com/jpcima/HybridReverb2
UI:           None
JACK Name:    HybridReverb2
Sample rate:  48000 Hz
Block length: 256 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz
```
Et le terminal ne me rend pas la main. Si je lance Catia, je ne le vois pas apparaître.

2. version 1.6.0~dfsg0-2 (la version actuelle de debian)

3. j'ai essayé avec Qtractor mais il ne le reconnait pas

**Comment by trebmuh** [comment]
Merci pour la solution trouvée sur IRC @jpcima .
Il fallait ajouter les [IR](http://www2.ika.ruhr-uni-bochum.de/HybridReverb2/HybridReverb2_large_database.zip) et les placer dans `/usr/share/HybridReverb2/`.

Je ferme ici du coup.
