### ISSUE TITLE
IR database downloader

### ISSUE THREAD

**Issue by jpcima** [jpcima/HybridReverb2#3]
Have a component which will download the IR from the academic site, when the plugin is launched the first time.
It will save the necessity to package the proprietary IR database for its setup.

**Comment by jpcima** [comment]
@trebmuh j'ai codé une solution permettant le téléchargement des IR.
Si ce n'est pas un téléchargeur à proprement parler, cela permet une installation depuis Internet ou le disque dur, au choix.

![screenshot at 2018-06-24 12-26-34](https://user-images.githubusercontent.com/17614485/41818194-e1161722-77a9-11e8-9d59-e34d044b417b.png)

**Comment by jpcima** [comment]
D'autre part, il n'est plus nécessaire d'installer des fichiers de configuration, ce qui allège le processus d'installation et aussi le code.
Tout s'installe à l'intérieur du dossier de l'utilisateur `.config/HybridReverb2`.

PS. j'ai lu le mail adressé à nos amis académiciens, parfaitement formulé et argumenté. 20/20

**Comment by trebmuh** [comment]
Super !
C'est possible de préciser le "copyright notice" avec :

> These room impulse responses for HybridReverb2 are property of the Institute of Communication Acoustics, Ruhr Universität Bochum, Germany http://www.ruhr-uni-bochum.de/ika/ . They are free for non-commercial use. For commercial use, please contact <rainer.martin@ruhr-uni-bochum.de>. They were generated with the "tinyAVE" software.

?

**Comment by jpcima** [comment]
Oui

**Comment by trebmuh** [comment]
Super !

C'est un chouette contournement qui va me permettre de redistribuer le logiciel, en attendant une réponse des universitaires.

Aller hop, je relance une construction pour voir ça.

**Comment by jpcima** [comment]
L'IGU se bloquera pendant que fichier zip se désarchive.
Pour bien faire, il faudrait faire ça en tâche asynchrone et mettre un indicateur d'attente.

**Comment by trebmuh** [comment]
La constuction fonctionne et j'aime bien la neutralité de la technique que tu as mis en place (par téléchargement).
Merci @jpcima !

+1 pour l'idée de l'indicateur d'attente

**Comment by jpcima** [comment]
Problème résolu
