### ISSUE TITLE
Problème de git clone

### ISSUE THREAD

**Issue by trebmuh** [jpcima/HybridReverb2#6]
```
$ git clone https://github.com/jpcima/HybridReverb2.git --recursive
Clonage dans 'HybridReverb2'...
remote: Counting objects: 282, done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 282 (delta 165), reused 246 (delta 132), pack-reused 0
Réception d'objets: 100% (282/282), 429.00 KiB | 439.00 KiB/s, fait.
Résolution des deltas: 100% (165/165), fait.
Sous-module 'Thirdparty/JUCE' (https://github.com/jpcima/JUCE.git) enregistré pour le chemin 'Thirdparty/JUCE'
Clonage dans 'xxxx/HybridReverb2/Thirdparty/JUCE'...
remote: Counting objects: 170923, done.        
remote: Compressing objects: 100% (15/15), done.        
remote: Total 170923 (delta 15), reused 8 (delta 8), pack-reused 170900        
Réception d'objets: 100% (170923/170923), 203.70 MiB | 718.00 KiB/s, fait.
Résolution des deltas: 100% (134179/134179), fait.
error: no such remote ref d492f3b666808ce712e84d52de711e9503c7302d
Chemin de sous-module 'Thirdparty/JUCE' récupéré, mais il ne contenait pas d492f3b666808ce712e84d52de711e9503c7302d. La récupération directe de ce commit a échoué.
```

**Comment by jpcima** [comment]
J'ignore à quel moment c'est arrivé. Une erreur de ma part.
Tentative d'arranger ça

**Comment by trebmuh** [comment]
Merci de l'avoir corrigé!
Je ferme.

**Comment by magnetophon** [comment]
I think I have the same issue now:
```
fatal: reference is not a tree: 78aec68237daa504c3ef87fc03e010695ace6684
Unable to checkout 78aec68237daa504c3ef87fc03e010695ace6684 from https://github.com/jpcima/JUCE.git.
```

**Comment by trebmuh** [comment]
@magnetophon : I've just tried and all went fine. Might that have been a temporary internet glitch?

**Comment by magnetophon** [comment]
@trebmuh Thanks for the quick reply.
On closer inspection, I seem to have a different issue after all.
A regular recursive clone works just fine, as you mentioned.
When I try to build the package with nix, I get the error I mentioned above.
Still investigating this one.

Sorry for the noise!

**Comment by magnetophon** [comment]
It looks like the problem I'm seeing might come from this repo after all.
@jtojnar mentioned in [a comment](https://github.com/NixOS/nixpkgs/issues/104048#issuecomment-730696721):
```
The broken hash comes from HybridReverb2 repo: https://github.com/jpcima/HybridReverb2/tree/v2.1.1/Thirdparty

Looks like they use their own JUCE fork and force pushed so the commit used by HR 2.1.1 has been garbage collected on GitHub.
```

**Comment by jpcima** [comment]
@magnetophon Hi

I've no idea what's off here. The submodule points to a commit hash which exists in the remote.
However it doesn't seem to connect to the branch by its name, only top commit hash. (is this a problem?)

Running `git clone --recursive` will indeed clone the whole with success. That's with `git version 2.29.2`.
Are you using a different configuration?

**Comment by jtojnar** [comment]
The problem is not on master but on 2.1.1. Try to checkout the tag and then do a submodule update.

**Comment by jpcima** [comment]
Ok I see, it makes sense.
The easier is that I tag a new version 2.1.2, will that be fine with you?

**Comment by magnetophon** [comment]
> The easier is that I tag a new version 2.1.2, will that be fine with you?

Sure, thanks!

**Comment by jpcima** [comment]
Ok I pushed the tag, let me know if this works.

**Comment by magnetophon** [comment]
Thanks!
